server:
  port: 8080

spring:
  application.name: Spring Blueprint

  datasource:
    url: jdbc:postgresql://localhost:4321/SampleDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

logging.level:
  root: INFO
  co.in.nextgencoder.springblueprint: DEBUG
  org.springframework.web: TRACE
  org.hibernate.SQL: DEBUG